### ISSUE TITLE
Fix Routing on github pages

### ISSUE THREAD

**Issue by RohrerF** [RohrerF/factorygame#45]
## Expected Behavior

routes to `https://rohrerf.github.io/factorygame/shop` 

## Actual Behavior

routes to `https://rohrerf.github.io/shop`

**Comment by maracuja-juice** [comment]
I think there are two solutions for this:
1. 
```
We need to ensure that we are using aHashRouter instead of the typical BrowserRouter.
The difference is that the hashRouter adds a ‘#’ into the url and 
upon a refresh of the page you will not see a 404 Github Error
```
2. [Single Page App Github Pages](https://github.com/rafrex/spa-github-pages)

**Comment by RohrerF** [comment]
No longer necessary as it is now hosted on xxxNo longer necessary as it is now hosted on netlify
